import {
	AvatarAngelaGray,
	AvatarAnnaKim,
	AvatarJacobThompson,
	AvatarKimberlySmith,
	AvatarMarkWebber,
	AvatarNathanPeterson,
	AvatarRizkyHasanuddin,
	ImageChess,
} from "../assets/IndexImages";

export const accounts = [
	{
		id: "mark-webber",
		avatar: AvatarMarkWebber,
		name: "Mark Webber ",
		alt: "Mark Webber Avatar",
		about: "reacted to your recent posts ",
		destiny: "My first tournament today! ",
		status: "  🔴 ",
		time: "1m ago",
		pm: "",
		imageCommented: "",
		altImageCommented: "",
		isHasChildren: false,
	},
	{
		id: "angela-gray",
		avatar: AvatarAngelaGray,
		name: "Angela Gray ",
		alt: "Angela Gray Avatar",
		about: "followed you ",
		destiny: "",
		status: "  🔴 ",
		time: "5m ago",
		pm: "",
		imageCommented: "",
		altImageCommented: "",
		isHasChildren: false,
	},
	{
		id: "jacob-thompson",
		avatar: AvatarJacobThompson,
		name: "Jacob Thompson ",
		alt: "Jacob Thompson Avatar",
		about: "has joined your group ",
		destiny: "Chess Club ",
		status: "  🔴 ",
		time: "1day ago",
		pm: "",
		imageCommented: "",
		altImageCommented: "",
		classAbout: "text-primary-blue font-bold cursor-pointer",
		isHasChildren: false,
	},
	{
		id: "rizky-hasanuddin",
		avatar: AvatarRizkyHasanuddin,
		name: "Rizky Hasanuddin ",
		alt: "Rizky Hasanuddin Avatar",
		about: "sent your a private message ",
		destiny: "",
		status: "",
		time: "1day ago",
		pm: "Hello, thanks for setting up the Chess Club. I've been a member for a few weeks now and I'm already having lots of fun and improving my game.",
		imageCommented: "",
		altImageCommented: "",
		classCard:
			"flex flex-col md:flex-row md:max-w-xl rounded-md bg-netral-white sm:pb-4 p-2 shadow-none",
		isHasChildren: true,
	},
	{
		id: "kimberly-smith",
		avatar: AvatarKimberlySmith,
		name: "Kimberly Smith ",
		alt: "Kimberly Smith Avatar",
		about: "commented on your picture ",
		destiny: "",
		status: "",
		time: "1weeks ago",
		pm: "",
		imageCommented: ImageChess,
		altImageCommented: "Image Chess Commented",
		classCard:
			"flex flex-col md:flex-row md:max-w-xl sm:w-[250px] md:w-[500px] rounded-md bg-netral-white p-2 shadow-none",
		isHasChildren: false,
	},
	{
		id: "nathan-peterson",
		avatar: AvatarNathanPeterson,
		name: "Nathan Peterson ",
		alt: "Nathan Peterson Avatar",
		about: "reacted to your recent post ",
		destiny: "5 end-game strategies to increase your win rate",
		time: "2weeks ago",
		pm: "",
		imageCommented: "",
		altImageCommented: "",
		classCard:
			"flex flex-col md:w-[520px] md:flex-row md:max-w-xl rounded-md bg-netral-white p-2",
		classABout:
			"text-netral-d-g-blue font-bold ease-in-out duration-150 hover:text-primary-blue cursor-pointer",
		isHasChildren: false,
	},
	{
		id: "anna-kim",
		avatar: AvatarAnnaKim,
		name: "Anna Kim ",
		alt: "Anna Kim Avatar",
		about: "left the group ",
		destiny: "Chess Club",
		time: "2weeks ago",
		pm: "",
		imageCommented: "",
		altImageCommented: "",
		classCard:
			"flex flex-col md:flex-row md:max-w-xl md:w-[500px] rounded-md bg-netral-white sm:mt-3 p-2 shadow-none",
		classAbout:
			"text-netral-v-d-blue ease-in-out duration-150 hover:text-primary-blue cursor-pointer font-medium cursor-pointer",
		isHasChildren: false,
	},
];

export const challenge = [
	{
		id: "challenge1",
		challengeBy: "Frontend Mentor",
		linkMentor: "https://www.frontendmentor.io?ref=challenge",
		CodedBy: "Guido Famula",
		linkCoder: "https://guidofamula.com/",
	},
];
